server:
  port: 8080

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true

spring:
  application.name: backend-user
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: service-books-id
          uri: lb://service-books
          predicates:
            Path=/books/**
        - id: service-prices-id
          uri: lb://service-prices
          predicates:
            Path=/prices/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka